/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kunanan
 */
public class Start extends javax.swing.JFrame {

    Person person = null;

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        this.setLocationRelativeTo(null);
        welcome.setVisible(true);
        loginPanel.setVisible(false);
        historyPanel.setVisible(false);
        searchMenu.setVisible(false);
        incomeSearch.setVisible(false);
        expenseSearch.setVisible(false);
        saveSearch.setVisible(false);
        registerPanel.setVisible(false);
        menuPanel.setVisible(false);
        incomePanel.setVisible(false);
        expensePanel.setVisible(false);
        savePanel.setVisible(false);
        summaryPanel.setVisible(false);
        registerPanel.setVisible(false);
        this.setVisible(true);
        this.setSize(360, 680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyPanel = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        hisShow = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        incomeButton = new javax.swing.JButton();
        expenseButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        allsumButton = new javax.swing.JButton();
        showIn = new javax.swing.JLabel();
        showEx = new javax.swing.JLabel();
        showSa = new javax.swing.JLabel();
        showTo = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        historyButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        printData = new javax.swing.JButton();
        hi = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        regisButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        savePanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        amountSave = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        noteSave = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        incomePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        amountIn = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        noteIn = new javax.swing.JTextPane();
        Save = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        sumIn = new javax.swing.JLabel();
        sumEx = new javax.swing.JLabel();
        sumSa = new javax.swing.JLabel();
        sumTo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accId = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        pas = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        expensePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountEx = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteEx = new javax.swing.JTextPane();
        Save2 = new javax.swing.JButton();
        Back2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        welcome = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        searchMenu = new javax.swing.JPanel();
        inSearch = new javax.swing.JButton();
        exSearch = new javax.swing.JButton();
        saSearch = new javax.swing.JButton();
        backInSearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        incomeSearch = new javax.swing.JPanel();
        searchBar1 = new javax.swing.JTextField();
        s1 = new javax.swing.JButton();
        clearBtn1 = new javax.swing.JButton();
        backbtn1 = new javax.swing.JButton();
        wrong = new javax.swing.JScrollPane();
        inSearchField = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        expenseSearch = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        exSearchField = new javax.swing.JTextArea();
        clearBtn2 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        backbtn2 = new javax.swing.JButton();
        searchBar2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        saveSearch = new javax.swing.JPanel();
        searchBar3 = new javax.swing.JTextField();
        clearBtn3 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        saSearchField = new javax.swing.JTextArea();
        backBtn3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        historyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("Print");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        historyPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 70, -1));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        historyPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 70, -1));

        hisShow.setColumns(20);
        hisShow.setRows(5);
        jScrollPane7.setViewportView(hisShow);

        historyPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, 360));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/history.png"))); // NOI18N
        historyPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 360, 680));

        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incomeButton.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        incomeButton.setText("INCOME");
        incomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeButtonActionPerformed(evt);
            }
        });
        menuPanel.add(incomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 90, -1));

        expenseButton.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        expenseButton.setText("EXPENSE");
        expenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseButtonActionPerformed(evt);
            }
        });
        menuPanel.add(expenseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, -1));

        saveButton.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        menuPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 70, 30));

        allsumButton.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        allsumButton.setText("SUMMARY");
        allsumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allsumButtonActionPerformed(evt);
            }
        });
        menuPanel.add(allsumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 30));
        menuPanel.add(showIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 30));
        menuPanel.add(showEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 70, 20));
        menuPanel.add(showSa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 70, 20));

        showTo.setForeground(new java.awt.Color(254, 254, 254));
        menuPanel.add(showTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 90, 20));
        menuPanel.add(showName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 70, 20));

        historyButton.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        historyButton.setText("HISTORY");
        historyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        menuPanel.add(historyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, 30));

        searchButton.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        menuPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 80, 30));

        printData.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        printData.setText("PRINT");
        printData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDataActionPerformed(evt);
            }
        });
        menuPanel.add(printData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, 30));

        hi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/menuV2.jpg"))); // NOI18N
        menuPanel.add(hi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 340, 670));

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Username");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel3.setText("Password");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        loginPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 150, -1));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        loginPanel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 150, -1));

        loginButton.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 70, 30));

        regisButton.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        regisButton.setText("Register");
        regisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisButtonActionPerformed(evt);
            }
        });
        loginPanel.add(regisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 80, 30));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/login.png"))); // NOI18N
        jLabel4.setText(" ");
        loginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 340, 680));

        savePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setViewportView(amountSave);

        savePanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 150, 30));

        jScrollPane6.setViewportView(noteSave);

        savePanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, 30));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        savePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 60, 30));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        savePanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 60, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/save.jpg"))); // NOI18N
        savePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 620));

        incomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(amountIn);

        incomePanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, 30));

        jScrollPane4.setViewportView(noteIn);

        incomePanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 30));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        incomePanel.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 70, 40));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        incomePanel.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 70, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/income.png"))); // NOI18N
        incomePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 640));

        summaryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        summaryPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 540, 90, -1));
        summaryPanel.add(sumIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 160, 50));
        summaryPanel.add(sumEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 160, 40));
        summaryPanel.add(sumSa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 80, 50));
        summaryPanel.add(sumTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 160, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/summary.png"))); // NOI18N
        summaryPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 640));

        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        registerPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 80, 30));

        jLabel7.setText("Account ID");
        registerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 80, 30));

        jLabel8.setText("Username");
        registerPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jLabel9.setText("Password");
        registerPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, 30));

        accId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accIdActionPerformed(evt);
            }
        });
        registerPanel.add(accId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, -1));
        registerPanel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, -1));

        jButton7.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        registerPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 30));
        registerPanel.add(pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/regis.jpg"))); // NOI18N
        registerPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 650));

        expensePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(amountEx);

        expensePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 30));

        jScrollPane2.setViewportView(noteEx);

        expensePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 150, 30));

        Save2.setText("Save");
        Save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save2ActionPerformed(evt);
            }
        });
        expensePanel.add(Save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 70, 30));

        Back2.setText("Back");
        Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2ActionPerformed(evt);
            }
        });
        expensePanel.add(Back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/expense.png"))); // NOI18N
        expensePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 640));

        welcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Enter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        welcome.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 80, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/welcome.png"))); // NOI18N
        welcome.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 350, 658));

        searchMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inSearch.setText("INCOME");
        inSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSearchActionPerformed(evt);
            }
        });
        searchMenu.add(inSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 60));

        exSearch.setText("EXPENSE");
        exSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exSearchActionPerformed(evt);
            }
        });
        searchMenu.add(exSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 250, 60));

        saSearch.setText("EXTRA SAVE");
        saSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saSearchActionPerformed(evt);
            }
        });
        searchMenu.add(saSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 250, 60));

        backInSearch.setBackground(new java.awt.Color(254, 219, 1));
        backInSearch.setIcon(new javax.swing.ImageIcon("/home/kunanan/Desktop/IncomeExpenseLogin/src/incomeexpenselogin/image/arrow2.jpg")); // NOI18N
        backInSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backInSearchActionPerformed(evt);
            }
        });
        searchMenu.add(backInSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 30, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/searchMenu.jpg"))); // NOI18N
        searchMenu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 360, 680));

        incomeSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBar1ActionPerformed(evt);
            }
        });
        incomeSearch.add(searchBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, 30));

        s1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        s1.setText("Search");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        incomeSearch.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 30));

        clearBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/eraser.png"))); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        incomeSearch.add(clearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 70, 20));

        backbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/arrow2.jpg"))); // NOI18N
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });
        incomeSearch.add(backbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 20, 20));

        inSearchField.setColumns(20);
        inSearchField.setRows(5);
        wrong.setViewportView(inSearchField);

        incomeSearch.add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, 340));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/_340635income_fun.png"))); // NOI18N
        incomeSearch.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 360, 810));

        jTextField2.setText("jTextField2");
        incomeSearch.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        expenseSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exSearchField.setColumns(20);
        exSearchField.setRows(5);
        jScrollPane8.setViewportView(exSearchField);

        expenseSearch.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, 340));

        clearBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/eraser.png"))); // NOI18N
        clearBtn2.setText("Clear");
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });
        expenseSearch.add(clearBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 80, 20));

        s2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        s2.setText("Search");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        expenseSearch.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));

        backbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/arrow2.jpg"))); // NOI18N
        backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn2ActionPerformed(evt);
            }
        });
        expenseSearch.add(backbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 20, 30));
        expenseSearch.add(searchBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/_340635expense_fun.png"))); // NOI18N
        expenseSearch.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 340, 670));

        saveSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBar3.setBackground(new java.awt.Color(254, 254, 254));
        searchBar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBar3ActionPerformed(evt);
            }
        });
        saveSearch.add(searchBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        clearBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/eraser.png"))); // NOI18N
        clearBtn3.setText("Clear");
        clearBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn3ActionPerformed(evt);
            }
        });
        saveSearch.add(clearBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 70, 20));

        s3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        s3.setText("Search");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        saveSearch.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));

        saSearchField.setColumns(20);
        saSearchField.setRows(5);
        jScrollPane9.setViewportView(saSearchField);

        saveSearch.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, 340));

        backBtn3.setBackground(new java.awt.Color(255, 189, 51));
        backBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/arrow2.jpg"))); // NOI18N
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });
        saveSearch.add(backBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 20, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/_340635extraa_fun.png"))); // NOI18N
        saveSearch.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 360, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(incomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(expensePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(457, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(incomeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(expenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(incomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(expensePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(incomeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(expenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String userString = username.getText();
        String passwordString = String.valueOf(pass.getPassword());
        try {
            if (Person.checkUser(userString, passwordString)) {
                JOptionPane.showMessageDialog(null, "Login is Success");
                loginPanel.setVisible(false);
                menuPanel.setVisible(true);
                person = new Person(userString);
                String i = Double.toString(person.getIncome());
                String e = Double.toString(person.getExpense());
                String s = Double.toString(person.getTotalSave());
                String t = Double.toString(person.getTotal());
                String n = person.getPerName();
                showIn.setText(i);
                showEx.setText(e);
                showSa.setText(s);
                showTo.setText(t);
                showName.setText(n);
            } else {
                JOptionPane.showMessageDialog(null, "Username, Password incorrect or can't be empty field", "Somthing Wrong", JOptionPane.ERROR_MESSAGE);
                pass.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void regisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisButtonActionPerformed
        registerPanel.setVisible(true);
        loginPanel.setVisible(false);
    }//GEN-LAST:event_regisButtonActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void incomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeButtonActionPerformed
        incomePanel.setVisible(true);
        menuPanel.setVisible(false);
    }//GEN-LAST:event_incomeButtonActionPerformed

    private void expenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseButtonActionPerformed
        menuPanel.setVisible(false);
        expensePanel.setVisible(true);
    }//GEN-LAST:event_expenseButtonActionPerformed

    private void allsumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allsumButtonActionPerformed
        summaryPanel.setVisible(true);
        menuPanel.setVisible(false);
        double analyIn = (person.getIncome() / person.getSumin_ex()) * 100;
        double analyEx = (person.getExpense() / person.getSumin_ex()) * 100;
        double tmp1 = Math.round(analyIn);
        double tmp2 = Math.round(analyEx);

        String a = Double.toString(tmp1);
        String b = Double.toString(tmp2);
        String c = Double.toString((person.getTotalSave()));
        String d = Double.toString(person.getTotal());
        sumIn.setText("             " + a + " %");;
        sumEx.setText("             " + b + " %");;
        sumSa.setText(c + " Baht");;
        sumTo.setText(d + " Baht");;

    }//GEN-LAST:event_allsumButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int check = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Would You Like to Save your?", "Warning", check);
        if (check == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            remove(check);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Date day = null;
        String tmp = amountIn.getText();
        String note = noteIn.getText();

        if (tmp.equals("")) {
            JOptionPane.showMessageDialog(null, "Input some amount / Can't be empty field", "Warning ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                double amount = Double.parseDouble(tmp);
                person.addIncome(person.getPerId(), day, note, amount);
                String i = Double.toString(person.getIncome());
                String e = Double.toString(person.getExpense());
                String s = Double.toString(person.getTotalSave());
                String t = Double.toString(person.getTotal());
                String n = person.getPerName();
                showIn.setText(i);
                showEx.setText(e);
                showSa.setText(s);
                showTo.setText(t);
                showName.setText(n);
                amountIn.setText("");
                noteIn.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
            }
            person.update();
            JOptionPane.showMessageDialog(null, "Add Income Complete", "Success ", JOptionPane.INFORMATION_MESSAGE);
            incomePanel.setVisible(false);
            menuPanel.setVisible(true);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        amountIn.setText("");
        noteIn.setText("");
        incomePanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2ActionPerformed
        amountEx.setText("");
        noteEx.setText("");
        expensePanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_Back2ActionPerformed

    private void Save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save2ActionPerformed
        Date day = null;
        String tmp = amountEx.getText();
        String note = noteEx.getText();

        if (tmp.equals("")) {
            JOptionPane.showMessageDialog(null, "Input some amount / Can't be empty field", "Warning ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                double amount = Double.parseDouble(amountEx.getText());
                person.addExpense(person.getPerId(), day, note, amount);
                String i = Double.toString(person.getIncome());
                String e = Double.toString(person.getExpense());
                String s = Double.toString(person.getTotalSave());
                String t = Double.toString(person.getTotal());
                String n = person.getPerName();
                showIn.setText(i);
                showEx.setText(e);
                showSa.setText(s);
                showTo.setText(t);
                showName.setText(n);
                amountEx.setText("");
                noteEx.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
            }
            person.update();
            JOptionPane.showMessageDialog(null, "Add Expense Complete", "Success ", JOptionPane.INFORMATION_MESSAGE);
            expensePanel.setVisible(false);
            menuPanel.setVisible(true);
        }


    }//GEN-LAST:event_Save2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date day = null;
        String tmp = amountSave.getText();
        String note = noteSave.getText();

        if (tmp.equals("")) {
            JOptionPane.showMessageDialog(null, "Input some amount / Can't be empty field", "Warning ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                double amount = Double.parseDouble(amountSave.getText());
                person.addSave(person.getPerId(), day, note, amount);
                String i = Double.toString(person.getIncome());
                String e = Double.toString(person.getExpense());
                String s = Double.toString(person.getTotalSave());
                String t = Double.toString(person.getTotal());
                String n = person.getPerName();
                showIn.setText(i);
                showEx.setText(e);
                showSa.setText(s);
                showTo.setText(t);
                showName.setText(n);
                amountSave.setText("");
                noteSave.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
            }
            person.update();
            JOptionPane.showMessageDialog(null, "Add Save Complete", "Success ", JOptionPane.INFORMATION_MESSAGE);
            savePanel.setVisible(false);
            menuPanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        savePanel.setVisible(true);
        menuPanel.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        amountSave.setText("");
        noteSave.setText("");
        savePanel.setVisible(false);
        menuPanel.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        welcome.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void accIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accIdActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tmp = accId.getText();
        String use = user.getText();
        String passwordString = String.valueOf(pas.getPassword());

        try {
            if (tmp.equals("") || use.equals("") || passwordString.equals("")) {
                JOptionPane.showMessageDialog(null, "Can't be empty field", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                int a = Integer.parseInt(tmp);
                Person.createUser(a, use, passwordString, 0, 0, 0, 0, 0);
                JOptionPane.showMessageDialog(null, "Register Complete", "Complete", JOptionPane.INFORMATION_MESSAGE);
                registerPanel.setVisible(false);
                loginPanel.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Account can't be string", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        registerPanel.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        summaryPanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        menuPanel.setVisible(false);
        historyPanel.setVisible(true);
        Scanner sc = new Scanner(System.in);
        String x;
        List<History> history = History.getHistory(person.getPerId());
        if (history != null) {
            int count = 1;
            for (History h : history) {
                if (count++ <= 1) {
                    hisShow.setText(hisShow.getText() + h.getHistoryDateTime() + "       " + h.getHistoryDescription() + "           " + h.getAmount() + "\n\n");
                } else {
                    hisShow.setText(hisShow.getText() + h.getHistoryDateTime() + "       " + h.getHistoryDescription() + "           " + h.getAmount() + "\n\n");
                }
            }
        }
    }//GEN-LAST:event_historyButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        historyPanel.setVisible(false);
        menuPanel.setVisible(true);
        hisShow.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        menuPanel.setVisible(false);
        searchMenu.setVisible(true);

    }//GEN-LAST:event_searchButtonActionPerformed

    private void backInSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backInSearchActionPerformed
        menuPanel.setVisible(true);
        searchMenu.setVisible(false);
    }//GEN-LAST:event_backInSearchActionPerformed

    private void inSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSearchActionPerformed
        searchMenu.setVisible(false);
        incomeSearch.setVisible(true);
    }//GEN-LAST:event_inSearchActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        inSearchField.setText("");
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        Scanner sc = new Scanner(System.in);
        try {
            Connection conn = ConnectionDB.getConnection();
            long a = person.getPerId();
            String search = searchBar1.getText();
 
            if (search.equals("")) {
                JOptionPane.showMessageDialog(null, "Can't be empty field", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                PreparedStatement ps = conn.prepareStatement("SELECT * FROM  INCOME WHERE PERID = " + a + "  and CATALOG LIKE '%" + search + "%' ");
                ResultSet rec = ps.executeQuery();

                if (!rec.next()) {
                    JOptionPane.showMessageDialog(null, "Information not found");
                } else {
                    do {
                        inSearchField.setText(inSearchField.getText() + rec.getDate("Days") + "          " + rec.getString("CATALOG") + "                     " + rec.getDouble("AMOUNT") + "\n\n");
                    } while (rec.next());
                }
                ps.close();
                conn.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_s1ActionPerformed

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed
        incomeSearch.setVisible(false);
        searchMenu.setVisible(true);
        searchBar1.setText("");
        inSearchField.setText("");
    }//GEN-LAST:event_backbtn1ActionPerformed

    private void searchBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBar1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        Scanner sc = new Scanner(System.in);
        try {
            Connection conn = ConnectionDB.getConnection();
            long a = person.getPerId();
            String search2 = searchBar2.getText();
 
            if (search2.equals("")) {
                JOptionPane.showMessageDialog(null, "Can't be empty field", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                PreparedStatement ps = conn.prepareStatement("SELECT * FROM  EXPENSE WHERE PERID = " + a + "  and CATALOG LIKE '%" + search2 + "%' ");
                ResultSet rec = ps.executeQuery();

                if (!rec.next()) {
                    JOptionPane.showMessageDialog(null, "Information not found");
                } else {
                    do {
                        exSearchField.setText(exSearchField.getText() + rec.getDate("Days") + "          " + rec.getString("CATALOG") + "                     " + rec.getDouble("AMOUNT") + "\n\n");
                    } while (rec.next());
                }
                ps.close();
                conn.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_s2ActionPerformed

    private void backbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn2ActionPerformed
        expenseSearch.setVisible(false);
        searchMenu.setVisible(true);
        searchBar2.setText("");
        exSearchField.setText("");
    }//GEN-LAST:event_backbtn2ActionPerformed

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        exSearchField.setText("");
    }//GEN-LAST:event_clearBtn2ActionPerformed

    private void exSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exSearchActionPerformed
        searchMenu.setVisible(false);
        expenseSearch.setVisible(true);
    }//GEN-LAST:event_exSearchActionPerformed

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        saveSearch.setVisible(false);
        searchMenu.setVisible(true);
        searchBar3.setText("");
        saSearchField.setText("");
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void clearBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn3ActionPerformed
        saSearchField.setText("");
    }//GEN-LAST:event_clearBtn3ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        Scanner sc = new Scanner(System.in);
        try {
            Connection conn = ConnectionDB.getConnection();
            long a = person.getPerId();
            String search3 = searchBar3.getText();
            
            if (search3.equals("")) {
                JOptionPane.showMessageDialog(null, "Can't be empty field", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                PreparedStatement ps = conn.prepareStatement("SELECT * FROM  SAVE WHERE PERID = " + a + "  and CATALOG LIKE '%" + search3 + "%' ");
                ResultSet rec = ps.executeQuery();

                if (!rec.next()) {
                    JOptionPane.showMessageDialog(null, "Information not found");
                } else {
                    do {
                        saSearchField.setText(saSearchField.getText() + rec.getDate("Days") + "          " + rec.getString("CATALOG") + "                     " + rec.getDouble("AMOUNT") + "\n\n");
                    } while (rec.next());
                }

                ps.close();
                conn.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_s3ActionPerformed

    private void saSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saSearchActionPerformed
        searchMenu.setVisible(false);
        saveSearch.setVisible(true);
    }//GEN-LAST:event_saSearchActionPerformed

    private void searchBar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBar3ActionPerformed

    private void printDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataActionPerformed

        try {
            Calendar calendar = Calendar.getInstance();
            java.util.Date date = calendar.getTime();

            Connection conn = ConnectionDB.getConnection();
            long a = person.getPerId();
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM  PERSONS WHERE PERID = " + a);
            ResultSet rec = ps.executeQuery();
            String path = "/home/kunanan/Desktop/IncomeExpenseLogin/src/incomeexpenselogin/textFile/userData.txt";
            FileWriter writer;
            try {
                File file = new File(path);
                writer = new FileWriter(file, false);  //True = Append to file, false = Overwrite
                while ((rec != null) && (rec.next())) {
                    writer.write("User ID : ");
                    writer.write(rec.getString("PERID"));
                    writer.write("\t\t\t\t\tUser name : ");
                    writer.write(rec.getString("PERNAME"));
                    writer.write("\n------------------------------------------------------------------------\n\n\tIncome \t\t\t\t\t ");
                    writer.write(rec.getString("INCOME"));
                    writer.write(" baht\n\tExpense \t\t\t\t ");
                    writer.write(rec.getString("EXPENSE"));
                    writer.write(" baht\n\tTotal Income&Expense   \t\t\t");
                    writer.write(rec.getString("SUMIN_EX"));
                    writer.write(" baht\n\tTotal Save \t\t\t\t ");
                    writer.write(rec.getString("TOTALSAVE"));
                    writer.write(" baht\n\tTotal \t\t\t\t\t ");
                    writer.write(rec.getString("TOTAL"));
                    writer.write(" baht\n\n\n");
                    writer.write("\t\t\t\t\t" + date + "\n");
                    writer.write("------------------------------------------------------------------------");
                }
                writer.close();
                ps.close();;
                conn.close();

                JOptionPane.showMessageDialog(null, "Print Data Complete", "Complete", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_printDataActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            Connection conn = ConnectionDB.getConnection();
            long a = person.getPerId();
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM  HISTORY WHERE PERID = " + a);
            ResultSet rec = ps.executeQuery();
            String path = "/home/kunanan/Desktop/IncomeExpenseLogin/src/incomeexpenselogin/textFile/historyGUI.txt";
            FileWriter writer;
            try {
                File file = new File(path);
                writer = new FileWriter(file, false);  //True = Append to file, false = Overwrite
                while ((rec != null) && (rec.next())) {

                    writer.write(rec.getString("HISTORY_DATE"));
                    writer.write("\t\t");
                    writer.write(rec.getString("HISTORY_CODE"));
                    writer.write("\t");
                    writer.write(rec.getString("AMOUNT"));
                    writer.write(" Baht \n\r\n");
                }
                writer.close();
                ps.close();;
                conn.close();

                JOptionPane.showMessageDialog(null, "Print Data Complete", "Complete", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Back2;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save2;
    private javax.swing.JTextField accId;
    private javax.swing.JButton allsumButton;
    private javax.swing.JTextPane amountEx;
    private javax.swing.JTextPane amountIn;
    private javax.swing.JTextPane amountSave;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backInSearch;
    private javax.swing.JButton backbtn1;
    private javax.swing.JButton backbtn2;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JButton clearBtn3;
    private javax.swing.JButton exSearch;
    private javax.swing.JTextArea exSearchField;
    private javax.swing.JButton expenseButton;
    private javax.swing.JPanel expensePanel;
    private javax.swing.JPanel expenseSearch;
    private javax.swing.JLabel hi;
    private javax.swing.JTextArea hisShow;
    private javax.swing.JButton historyButton;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JButton inSearch;
    private javax.swing.JTextArea inSearchField;
    private javax.swing.JButton incomeButton;
    private javax.swing.JPanel incomePanel;
    private javax.swing.JPanel incomeSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextPane noteEx;
    private javax.swing.JTextPane noteIn;
    private javax.swing.JTextPane noteSave;
    private javax.swing.JPasswordField pas;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton printData;
    private javax.swing.JButton regisButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton saSearch;
    private javax.swing.JTextArea saSearchField;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel savePanel;
    private javax.swing.JPanel saveSearch;
    private javax.swing.JTextField searchBar1;
    private javax.swing.JTextField searchBar2;
    private javax.swing.JTextField searchBar3;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchMenu;
    private javax.swing.JLabel showEx;
    private javax.swing.JLabel showIn;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel showSa;
    private javax.swing.JLabel showTo;
    private javax.swing.JLabel sumEx;
    private javax.swing.JLabel sumIn;
    private javax.swing.JLabel sumSa;
    private javax.swing.JLabel sumTo;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JTextField user;
    private javax.swing.JTextField username;
    private javax.swing.JPanel welcome;
    private javax.swing.JScrollPane wrong;
    // End of variables declaration//GEN-END:variables
}
